name: Build Chrome Extension

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Chrome Extension

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          RELEASE_BUILD: 1

      - name: Build Chrome extension
        run: pnpm package:chrome

      - name: Upload Chrome extension
        uses: actions/upload-artifact@v4
        with:
          name: linglook-chrome-${{ github.sha }}
          path: web-ext-artifacts/*.zip
          if-no-files-found: error
